
platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'HtmlParserDemo'

pod 'hpple', '~> 0.2.0'

target :HtmlParserDemoTests do
  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta', '~> 0.3.1'
  pod 'OCMockito',  '~> 1.3.1'
end

